### ISSUE TITLE
配置环境时BASICSR_EXT=True pip install basicsr报错，手动安装basicsr后测试图片无法保存，有测试结果，无法保存图片

### ISSUE THREAD

**Issue by svoeff** [csxmli2016/MARCONet#22]
Restoring syn_lq03.png. The predicted text: 的地址就是不知道要把它添加在
Traceback (most recent call last):
  File "test_sr.py", line 266, in main
    prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 62, in forward
    return self.TextGenerator(styles, labels, noise)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 140, in forward
    styles = self.style_mlp(styles)#
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 195, in forward
    out = fused_leaky_relu(out, bias)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward
    out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused_act_ext' is not defined
        Error in syn_lq03. Continue...
Restoring syn_lq04.png. The predicted text: 。应该可以玩！显卡很古老了，应该
Traceback (most recent call last):
  File "test_sr.py", line 266, in main
    prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 62, in forward
    return self.TextGenerator(styles, labels, noise)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 140, in forward
    styles = self.style_mlp(styles)#
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data/anmy/MARCONet/models/networks.py", line 195, in forward
    out = fused_leaky_relu(out, bias)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale)
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward
    out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused_act_ext' is not defined
        Error in syn_lq04. Continue...

**Comment by csxmli2016** [comment]
> Restoring syn_lq03.png. The predicted text: 的地址就是不知道要把它添加在 Traceback (most recent call last): File "test_sr.py", line 266, in main prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 62, in forward return self.TextGenerator(styles, labels, noise) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 140, in forward styles = self.style_mlp(styles)# File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward input = module(input) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 195, in forward out = fused_leaky_relu(out, bias) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale) NameError: name 'fused_act_ext' is not defined Error in syn_lq03. Continue... Restoring syn_lq04.png. The predicted text: 。应该可以玩！显卡很古老了，应该 Traceback (most recent call last): File "test_sr.py", line 266, in main prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 62, in forward return self.TextGenerator(styles, labels, noise) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 140, in forward styles = self.style_mlp(styles)# File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward input = module(input) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 195, in forward out = fused_leaky_relu(out, bias) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale) NameError: name 'fused_act_ext' is not defined Error in syn_lq04. Continue...

参考https://github.com/TencentARC/GFPGAN/issues/5#issuecomment-866492838

**Comment by svoeff** [comment]
非常感谢


发件人：csxmli2016 ***@***.***>
发送日期：2024-09-22 08:49:42
收件人：csxmli2016/MARCONet ***@***.***>
抄送人：suntaoran ***@***.***>, Author ***@***.***>
主 题：Re: [csxmli2016/MARCONet] 配置环境时BASICSR_EXT=True pip install basicsr报错，手动安装basicsr后测试图片无法保存，有测试结果，无法保存图片 (Issue #22)


Restoring syn_lq03.png. The predicted text: 的地址就是不知道要把它添加在 Traceback (most recent call last): File "test_sr.py", line 266, in main prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 62, in forward return self.TextGenerator(styles, labels, noise) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 140, in forward styles = self.style_mlp(styles)# File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward input = module(input) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 195, in forward out = fused_leaky_relu(out, bias) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale) NameError: name 'fused_act_ext' is not defined Error in syn_lq03. Continue... Restoring syn_lq04.png. The predicted text: 。应该可以玩！显卡很古老了，应该 Traceback (most recent call last): File "test_sr.py", line 266, in main prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 62, in forward return self.TextGenerator(styles, labels, noise) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 140, in forward styles = self.style_mlp(styles)# File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/container.py", line 219, in forward input = module(input) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl return forward_call(*args, **kwargs) File "/data/anmy/MARCONet/models/networks.py", line 195, in forward out = fused_leaky_relu(out, bias) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 95, in fused_leaky_relu return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale) File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/torch/autograd/function.py", line 574, in apply return super().apply(*args, **kwargs) # type: ignore[misc] File "/home/anmy/miniconda3/envs/marconet/lib/python3.8/site-packages/basicsr/ops/fused_act/fused_act.py", line 65, in forward out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale) NameError: name 'fused_act_ext' is not defined Error in syn_lq04. Continue...

参考TencentARC/GFPGAN#5 (comment)
