### ISSUE TITLE
NameError: name 'fused_act_ext' is not defined

### ISSUE THREAD

**Issue by fgogrrore4ft3w** [csxmli2016/MARCONet#23]
(marconet) C:\Users\L\Pictures\MARCONet>python test_sr.py -i "C:\Users\L\Downloads\bsrgan\inputs" --real_ocr
################################################################
                  Input Path : C:\Users\L\Downloads\bsrgan\inputs
                   Save Path : C:\Users\L\Downloads\bsrgan\inputs_11-10_16-59_MARCONet
    The format of text label : using predicted text label
                  OCR Module : using ocr model trained on public chinese ocr dataset (Preferred)
            New BBOX Network : 82.062941 M Parameters
  New Real-world OCR Network : 82.061916 M Parameters
         Transformer Encoder : 43.062275 M Parameters
     Structure Prior Network : 27.970194 M Parameters
    Super-Resolution Network : 16.865923 M Parameters
################################################################
!!!!!! Change the label from douailetp适用.con to 是多少的时间和图师买的？
Restoring testr-small.png. The predicted text: 是多少的时间和图师买的？
Traceback (most recent call last):
  File "test_sr.py", line 266, in main
    prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 62, in forward
    return self.TextGenerator(styles, labels, noise)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 140, in forward
    styles = self.style_mlp(styles)#
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\container.py", line 139, in forward
    input = module(input)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 195, in forward
    out = fused_leaky_relu(out, bias)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\basicsr\ops\fused_act\fused_act.py", line 95, in fused_leaky_relu
    return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale)
  File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\basicsr\ops\fused_act\fused_act.py", line 65, in forward
    out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale)
NameError: name 'fused_act_ext' is not defined
        Error in testr-small. Continue...

(marconet) C:\Users\L\Pictures\MARCONet>

I am aware that this topic has been covered multiple times in here , but I tried every solution and still encountering the same error

**Comment by csxmli2016** [comment]
> (marconet) C:\Users\L\Pictures\MARCONet>python test_sr.py -i "C:\Users\L\Downloads\bsrgan\inputs" --real_ocr ################################################################ Input Path : C:\Users\L\Downloads\bsrgan\inputs Save Path : C:\Users\L\Downloads\bsrgan\inputs_11-10_16-59_MARCONet The format of text label : using predicted text label OCR Module : using ocr model trained on public chinese ocr dataset (Preferred) New BBOX Network : 82.062941 M Parameters New Real-world OCR Network : 82.061916 M Parameters Transformer Encoder : 43.062275 M Parameters Structure Prior Network : 27.970194 M Parameters Super-Resolution Network : 16.865923 M Parameters ################################################################ !!!!!! Change the label from douailetp适用.con to 是多少的时间和图师买的？ Restoring testr-small.png. The predicted text: 是多少的时间和图师买的？ Traceback (most recent call last): File "test_sr.py", line 266, in main prior_cha, prior_fea64, prior_fea32 = modelTSPGAN(styles=w0.repeat(labels.size(0), 1), labels=labels, noise=None) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 62, in forward return self.TextGenerator(styles, labels, noise) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 140, in forward styles = self.style_mlp(styles)# File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\container.py", line 139, in forward input = module(input) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl return forward_call(*input, **kwargs) File "C:\Users\L\Pictures\MARCONet\models\networks.py", line 195, in forward out = fused_leaky_relu(out, bias) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\basicsr\ops\fused_act\fused_act.py", line 95, in fused_leaky_relu return FusedLeakyReLUFunction.apply(input, bias, negative_slope, scale) File "C:\Users\L\anaconda3\envs\marconet\lib\site-packages\basicsr\ops\fused_act\fused_act.py", line 65, in forward out = fused_act_ext.fused_bias_act(input, bias, empty, 3, 0, negative_slope, scale) NameError: name 'fused_act_ext' is not defined Error in testr-small. Continue...
> 
> (marconet) C:\Users\L\Pictures\MARCONet>
> 
> I am aware that this topic has been covered multiple times in here , but I tried every solution and still encountering the same error

If the solutions given in https://github.com/TencentARC/GFPGAN/issues/5#issuecomment-866492838 can not resolve this error, you may try to install a different version of pytorch and make sure the driver is consistent with pytorch cuda version.
