### ISSUE TITLE
Encountered error while generating package metadata.

### ISSUE THREAD

**Issue by YunjinChen** [csxmli2016/MARCONet#5]
running the last step: BASICSR_EXT=True pip install basicsr
an error happens. Any idea to solve it?

The above exception was the direct cause of the following exception:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-bposqbk9/basicsr_fb8418c801af48a4803eaa93cd2b1f3b/setup.py", line 147, in <module>
          setup(
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
          _install_setup_requires(attrs)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
          dist = self._resolve_dist(
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
          return self.obtain(req, installer)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
          return installer(requirement)
        File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/root/anaconda3/envs/marconet/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7br8i0db', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'cython']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by csxmli2016** [comment]
> running the last step: BASICSR_EXT=True pip install basicsr an error happens. Any idea to solve it?
> 
> The above exception was the direct cause of the following exception:
> 
> ```
>   Traceback (most recent call last):
>     File "<string>", line 2, in <module>
>     File "<pip-setuptools-caller>", line 34, in <module>
>     File "/tmp/pip-install-bposqbk9/basicsr_fb8418c801af48a4803eaa93cd2b1f3b/setup.py", line 147, in <module>
>       setup(
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 106, in setup
>       _install_setup_requires(attrs)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 79, in _install_setup_requires
>       _fetch_build_eggs(dist)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/__init__.py", line 84, in _fetch_build_eggs
>       dist.fetch_build_eggs(dist.setup_requires)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/dist.py", line 917, in fetch_build_eggs
>       return _fetch_build_eggs(self, requires)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
>       resolved_dists = pkg_resources.working_set.resolve(
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 827, in resolve
>       dist = self._resolve_dist(
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 863, in _resolve_dist
>       dist = best[req.key] = env.best_match(
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1133, in best_match
>       return self.obtain(req, installer)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1145, in obtain
>       return installer(requirement)
>     File "/root/anaconda3/envs/marconet/lib/python3.8/site-packages/setuptools/installer.py", line 98, in _fetch_build_egg_no_warn
>       raise DistutilsError(str(e)) from e
>   distutils.errors.DistutilsError: Command '['/root/anaconda3/envs/marconet/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmp7br8i0db', '--quiet', '--index-url', 'http://mirrors.cloud.aliyuncs.com/pypi/simple/', 'cython']' returned non-zero exit status 1.
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed
> 
> × Encountered error while generating package metadata. ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip. hint: See above for details.

I am also not sure about this problem. You may refer to the official repository https://github.com/XPixelGroup/BasicSR
